### ISSUE TITLE
[Suggestion] Add Elite and Champion bots

### ISSUE THREAD

**Issue by FruitAre** [windy10v10ai/game#1072]
**Bug type**

- [ ] Ability
- [ ] Item
- [ ] Hero
- [x] Bot
- [ ] UI
- [ ] Other

**Describe**
Add a toggle to the options screen that add an "elite" modifier to 3 dire bots and a "champion" modifier to 1 dire bot on game start that boosts their stats, or adds passive ability, similarly to player attributes.

**Expected behavior**
I think the challenge being less symmetrical would add variance to game play, there would be more reason to adjust strategy depending on which enemy bots get buffed and would make single-target important as well as AoE. Increasing gold multiplier for bots stops making the game harder, since that also increases kill bounty and players are more gold efficient.

**To Reproduce**
I would suggest putting bots into groups and giving bonuses that are effective endgame e.g.
Tank
%Incoming Damage Reduction, %Max Hp/Mp
Marksman
Attack Range, %Max Hp/Mp
Fighter
Movement Speed, Status Resist, %Str & Agi
Mage
Cast Range, Cooldown Reduction

**Screenshots**

**Comment by windybirth** [comment]
Implemented in #1138
