### ISSUE TITLE
[BUG] Attribute add on home page is bugged

### ISSUE THREAD

**Issue by unghuuduc** [windy10v10ai/game#1117]
**Bug type**

- [ ] Ability
- [ ] Item
- [ ] Hero
- [ ] Bot
- [ ] UI
- [x ] Other

**Describe the bug**
Attribute add on Home Page is bugged:

**Expected behavior**
It supposed to be +30 strength at level 6 according to the image

**To Reproduce**
Add +10 strength attribute on Home page and got to lv 4,6,...

**Screenshots**
![image](https://github.com/user-attachments/assets/bcd93fde-9dea-47dd-9393-47787a78a174)
![image](https://github.com/user-attachments/assets/7d0866a6-d411-45a2-adb6-3a89bbdce734)

**Comment by windybirth** [comment]
This seems to be unsolvable for the description, which has been resolved in the discussion on discord
https://discord.com/channels/883290352553955328/883291575717883904/1310998440293175376
